<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Manufacturer;
use App\Models\Product;
use App\Models\Stock;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class PharmacyItemsSeeder extends Seeder
{
    public function run(): void
    {
        $businessId = 1;

        // Ensure reference data exists
        $categories = $this->seedCategories($businessId);
        $manufacturers = $this->seedManufacturers($businessId);
        $units = $this->seedUnits($businessId);

        $items = [
            // ── Prescription Medicines ──
            [
                'productName' => 'Amoxicillin 500mg',
                'barcode' => '6001234567001',
                'sku' => 'RX-AMOX-500',
                'scientific_name' => 'Amoxicillin Trihydrate',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['square'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Capsule',
                'strength' => '500mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 45.00,
                'sales_price' => 65.00,
                'wholesale_price' => 58.00,
                'alert_qty' => 10,
                'reorder_point' => 20,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Amoxicillin',
                'dosage' => '1 capsule 3 times daily',
                'stock_qty' => 150,
                'batch_no' => 'BATCH-2026-A001',
                'expire_date' => '2027-06-15',
            ],
            [
                'productName' => 'Metformin 850mg',
                'barcode' => '6001234567002',
                'sku' => 'RX-METF-850',
                'scientific_name' => 'Metformin Hydrochloride',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['beximco'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '850mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 35.00,
                'sales_price' => 52.00,
                'wholesale_price' => 45.00,
                'alert_qty' => 15,
                'reorder_point' => 30,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Metformin HCl',
                'stock_qty' => 200,
                'batch_no' => 'BATCH-2026-M001',
                'expire_date' => '2027-12-01',
            ],
            [
                'productName' => 'Amlodipine 5mg',
                'barcode' => '6001234567003',
                'sku' => 'RX-AMLO-005',
                'scientific_name' => 'Amlodipine Besylate',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['aci'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '5mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 28.00,
                'sales_price' => 42.00,
                'wholesale_price' => 38.00,
                'alert_qty' => 10,
                'reorder_point' => 25,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Amlodipine',
                'stock_qty' => 120,
                'batch_no' => 'BATCH-2026-AL01',
                'expire_date' => '2027-09-20',
            ],
            [
                'productName' => 'Omeprazole 20mg',
                'barcode' => '6001234567004',
                'sku' => 'RX-OMEP-020',
                'scientific_name' => 'Omeprazole',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['acme'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Capsule',
                'strength' => '20mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 40.00,
                'sales_price' => 58.00,
                'wholesale_price' => 50.00,
                'alert_qty' => 8,
                'reorder_point' => 20,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Omeprazole',
                'stock_qty' => 90,
                'batch_no' => 'BATCH-2026-OM01',
                'expire_date' => '2027-11-10',
            ],
            [
                'productName' => 'Azithromycin 250mg',
                'barcode' => '6001234567005',
                'sku' => 'RX-AZIT-250',
                'scientific_name' => 'Azithromycin Dihydrate',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['apc'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '250mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 55.00,
                'sales_price' => 78.00,
                'wholesale_price' => 68.00,
                'alert_qty' => 10,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Azithromycin',
                'stock_qty' => 60,
                'batch_no' => 'BATCH-2026-AZ01',
                'expire_date' => '2027-08-15',
            ],

            // ── OTC Medicines ──
            [
                'productName' => 'Paracetamol 500mg',
                'barcode' => '6001234567006',
                'sku' => 'OTC-PARA-500',
                'scientific_name' => 'Acetaminophen',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['square'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '500mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 12.00,
                'sales_price' => 20.00,
                'wholesale_price' => 16.00,
                'alert_qty' => 30,
                'reorder_point' => 50,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Paracetamol',
                'stock_qty' => 500,
                'batch_no' => 'BATCH-2026-PA01',
                'expire_date' => '2028-01-20',
            ],
            [
                'productName' => 'Ibuprofen 400mg',
                'barcode' => '6001234567007',
                'sku' => 'OTC-IBU-400',
                'scientific_name' => 'Ibuprofen',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['beximco'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '400mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 18.00,
                'sales_price' => 30.00,
                'wholesale_price' => 25.00,
                'alert_qty' => 25,
                'reorder_point' => 40,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Ibuprofen',
                'stock_qty' => 350,
                'batch_no' => 'BATCH-2026-IB01',
                'expire_date' => '2028-03-10',
            ],
            [
                'productName' => 'Cetirizine 10mg',
                'barcode' => '6001234567008',
                'sku' => 'OTC-CETI-010',
                'scientific_name' => 'Cetirizine Hydrochloride',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['aci'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '10mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 15.00,
                'sales_price' => 25.00,
                'wholesale_price' => 20.00,
                'alert_qty' => 20,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Cetirizine HCl',
                'stock_qty' => 280,
                'batch_no' => 'BATCH-2026-CT01',
                'expire_date' => '2028-02-28',
            ],
            [
                'productName' => 'Pantoprazole 40mg',
                'barcode' => '6001234567009',
                'sku' => 'OTC-PANT-040',
                'scientific_name' => 'Pantoprazole Sodium',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['acme'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '40mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 32.00,
                'sales_price' => 48.00,
                'wholesale_price' => 42.00,
                'alert_qty' => 10,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Pantoprazole',
                'stock_qty' => 100,
                'batch_no' => 'BATCH-2026-PT01',
                'expire_date' => '2027-10-05',
            ],
            [
                'productName' => 'Loperamide 2mg',
                'barcode' => '6001234567010',
                'sku' => 'OTC-LOPE-002',
                'scientific_name' => 'Loperamide Hydrochloride',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['square'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Capsule',
                'strength' => '2mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 22.00,
                'sales_price' => 35.00,
                'wholesale_price' => 30.00,
                'alert_qty' => 15,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Loperamide HCl',
                'stock_qty' => 80,
                'batch_no' => 'BATCH-2026-LO01',
                'expire_date' => '2027-07-25',
            ],

            // ── Syrups & Liquid Formulations ──
            [
                'productName' => 'Amoxicillin Syrup 125mg/5ml',
                'barcode' => '6001234567011',
                'sku' => 'RX-AMOX-SYP',
                'scientific_name' => 'Amoxicillin Trihydrate',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['beximco'],
                'unit_id' => $units['bottle'],
                'dosage_form' => 'Syrup',
                'strength' => '125mg/5ml',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 38.00,
                'sales_price' => 55.00,
                'wholesale_price' => 48.00,
                'alert_qty' => 10,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Amoxicillin',
                'dosage' => '5ml 3 times daily',
                'package_size' => 100,
                'package_unit' => 'ml',
                'stock_qty' => 75,
                'batch_no' => 'BATCH-2026-AS01',
                'expire_date' => '2027-05-20',
            ],
            [
                'productName' => 'Cough Syrup (Multi)',
                'barcode' => '6001234567012',
                'sku' => 'OTC-COUG-SYP',
                'scientific_name' => 'Dextromethorphan + Guaifenesin',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['aci'],
                'unit_id' => $units['bottle'],
                'dosage_form' => 'Syrup',
                'strength' => '15mg/100ml',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 20.00,
                'sales_price' => 35.00,
                'wholesale_price' => 28.00,
                'alert_qty' => 15,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Dextromethorphan HBr',
                'package_size' => 120,
                'package_unit' => 'ml',
                'stock_qty' => 90,
                'batch_no' => 'BATCH-2026-CS01',
                'expire_date' => '2027-08-30',
            ],
            [
                'productName' => 'ORS Sachet',
                'barcode' => '6001234567013',
                'sku' => 'OTC-ORS-001',
                'scientific_name' => 'Oral Rehydration Salts',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['square'],
                'unit_id' => $units['box'],
                'dosage_form' => 'Powder for Solution',
                'strength' => '20.5g',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 8.00,
                'sales_price' => 15.00,
                'wholesale_price' => 12.00,
                'alert_qty' => 40,
                'reorder_point' => 60,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Sodium Chloride + Potassium Chloride',
                'package_size' => 10,
                'package_unit' => 'sachets',
                'stock_qty' => 300,
                'batch_no' => 'BATCH-2026-OR01',
                'expire_date' => '2028-04-01',
            ],

            // ── Injections ──
            [
                'productName' => 'Ceftriaxone 1g Injection',
                'barcode' => '6001234567014',
                'sku' => 'RX-CEFT-1G',
                'scientific_name' => 'Ceftriaxone Sodium',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['acme'],
                'unit_id' => $units['each'],
                'dosage_form' => 'Injection',
                'strength' => '1g',
                'route_of_administration' => 'Intravenous/Intramuscular',
                'purchase_with_tax' => 85.00,
                'sales_price' => 120.00,
                'wholesale_price' => 105.00,
                'alert_qty' => 8,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Ceftriaxone',
                'refrigerated' => false,
                'storage_instructions' => 'Store below 25°C, protect from light',
                'stock_qty' => 40,
                'batch_no' => 'BATCH-2026-CF01',
                'expire_date' => '2027-04-15',
            ],
            [
                'productName' => 'Insulin Glargine 100IU/ml',
                'barcode' => '6001234567015',
                'sku' => 'RX-INSU-GLA',
                'scientific_name' => 'Insulin Glargine',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['beximco'],
                'unit_id' => $units['each'],
                'dosage_form' => 'Injection',
                'strength' => '100IU/ml',
                'route_of_administration' => 'Subcutaneous',
                'purchase_with_tax' => 350.00,
                'sales_price' => 480.00,
                'wholesale_price' => 420.00,
                'alert_qty' => 5,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Insulin Glargine',
                'refrigerated' => true,
                'temperature_requirements' => '2-8°C',
                'storage_instructions' => 'Refrigerate. Do not freeze. Store in use at room temperature for up to 28 days.',
                'stock_qty' => 15,
                'batch_no' => 'BATCH-2026-IG01',
                'expire_date' => '2027-03-01',
            ],

            // ── Topical ──
            [
                'productName' => 'Betamethasone Cream 0.05%',
                'barcode' => '6001234567016',
                'sku' => 'OTC-BETA-CRM',
                'scientific_name' => 'Betamethasone Valerate',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['aci'],
                'unit_id' => $units['each'],
                'dosage_form' => 'Cream',
                'strength' => '0.05%',
                'route_of_administration' => 'Topical',
                'purchase_with_tax' => 15.00,
                'sales_price' => 25.00,
                'wholesale_price' => 20.00,
                'alert_qty' => 15,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Betamethasone Valerate',
                'package_size' => 15,
                'package_unit' => 'g',
                'stock_qty' => 120,
                'batch_no' => 'BATCH-2026-BT01',
                'expire_date' => '2027-09-10',
            ],
            [
                'productName' => 'Clotrimazole Cream 1%',
                'barcode' => '6001234567017',
                'sku' => 'OTC-CLOTR-CRM',
                'scientific_name' => 'Clotrimazole',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['square'],
                'unit_id' => $units['each'],
                'dosage_form' => 'Cream',
                'strength' => '1%',
                'route_of_administration' => 'Topical',
                'purchase_with_tax' => 12.00,
                'sales_price' => 22.00,
                'wholesale_price' => 18.00,
                'alert_qty' => 12,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Clotrimazole',
                'package_size' => 20,
                'package_unit' => 'g',
                'stock_qty' => 95,
                'batch_no' => 'BATCH-2026-CL01',
                'expire_date' => '2027-11-25',
            ],

            // ── Baby Care ──
            [
                'productName' => 'Baby Diaper Cream',
                'barcode' => '6001234567018',
                'sku' => 'OTC-BABY-DCR',
                'scientific_name' => 'Zinc Oxide',
                'category_id' => $categories['baby'],
                'manufacturer_id' => $manufacturers['acme'],
                'unit_id' => $units['each'],
                'dosage_form' => 'Cream',
                'strength' => '40%',
                'route_of_administration' => 'Topical',
                'purchase_with_tax' => 25.00,
                'sales_price' => 40.00,
                'wholesale_price' => 35.00,
                'alert_qty' => 10,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Zinc Oxide',
                'package_size' => 100,
                'package_unit' => 'g',
                'stock_qty' => 60,
                'batch_no' => 'BATCH-2026-BD01',
                'expire_date' => '2028-06-01',
            ],
            [
                'productName' => 'Infant Vitamin Drops',
                'barcode' => '6001234567019',
                'sku' => 'OTC-INFV-DRP',
                'scientific_name' => 'Multivitamin Drops',
                'category_id' => $categories['baby'],
                'manufacturer_id' => $manufacturers['apc'],
                'unit_id' => $units['each'],
                'dosage_form' => 'Drops',
                'strength' => '1ml=25000IU',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 30.00,
                'sales_price' => 48.00,
                'wholesale_price' => 40.00,
                'alert_qty' => 8,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Vitamin A, C, D3',
                'package_size' => 30,
                'package_unit' => 'ml',
                'stock_qty' => 45,
                'batch_no' => 'BATCH-2026-ID01',
                'expire_date' => '2027-12-15',
            ],

            // ── Surgical / Medical Devices ──
            [
                'productName' => 'Digital Thermometer',
                'barcode' => '6001234567020',
                'sku' => 'SRG-THER-DG',
                'scientific_name' => null,
                'category_id' => $categories['surgical'],
                'manufacturer_id' => null,
                'unit_id' => $units['each'],
                'dosage_form' => null,
                'strength' => null,
                'route_of_administration' => null,
                'purchase_with_tax' => 45.00,
                'sales_price' => 85.00,
                'wholesale_price' => 70.00,
                'alert_qty' => 5,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => false,
                'stock_qty' => 30,
                'batch_no' => 'SRG-2026-T01',
                'expire_date' => null,
            ],
            [
                'productName' => 'Blood Pressure Monitor',
                'barcode' => '6001234567021',
                'sku' => 'SRG-BPM-001',
                'scientific_name' => null,
                'category_id' => $categories['surgical'],
                'manufacturer_id' => null,
                'unit_id' => $units['each'],
                'dosage_form' => null,
                'strength' => null,
                'route_of_administration' => null,
                'purchase_with_tax' => 280.00,
                'sales_price' => 450.00,
                'wholesale_price' => 380.00,
                'alert_qty' => 3,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => false,
                'stock_qty' => 12,
                'batch_no' => 'SRG-2026-BP01',
                'expire_date' => null,
            ],
            [
                'productName' => 'Surgical Gloves (L) Box/100',
                'barcode' => '6001234567022',
                'sku' => 'SRG-GLV-L100',
                'scientific_name' => null,
                'category_id' => $categories['surgical'],
                'manufacturer_id' => $manufacturers['apc'],
                'unit_id' => $units['box'],
                'dosage_form' => null,
                'strength' => null,
                'route_of_administration' => null,
                'purchase_with_tax' => 35.00,
                'sales_price' => 55.00,
                'wholesale_price' => 45.00,
                'alert_qty' => 10,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => false,
                'package_size' => 100,
                'package_unit' => 'pieces',
                'stock_qty' => 80,
                'batch_no' => 'SRG-2026-GL01',
                'expire_date' => null,
            ],
            [
                'productName' => 'Disposable Syringe 5ml (Box/50)',
                'barcode' => '6001234567023',
                'sku' => 'SRG-SYR-5ML',
                'scientific_name' => null,
                'category_id' => $categories['surgical'],
                'manufacturer_id' => $manufacturers['acme'],
                'unit_id' => $units['box'],
                'dosage_form' => null,
                'strength' => null,
                'route_of_administration' => null,
                'purchase_with_tax' => 22.00,
                'sales_price' => 38.00,
                'wholesale_price' => 32.00,
                'alert_qty' => 20,
                'reorder_point' => 30,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => false,
                'package_size' => 50,
                'package_unit' => 'pieces',
                'stock_qty' => 150,
                'batch_no' => 'SRG-2026-SY01',
                'expire_date' => null,
            ],

            // ── Low-stock / Out-of-stock items for testing ──
            [
                'productName' => 'Metronidazole 400mg',
                'barcode' => '6001234567024',
                'sku' => 'RX-METR-400',
                'scientific_name' => 'Metronidazole',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['square'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '400mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 14.00,
                'sales_price' => 22.00,
                'wholesale_price' => 18.00,
                'alert_qty' => 20,
                'reorder_point' => 30,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Metronidazole',
                'stock_qty' => 3,
                'batch_no' => 'BATCH-2026-MT01',
                'expire_date' => '2027-05-10',
            ],
            [
                'productName' => 'Salbutamol Inhaler',
                'barcode' => '6001234567025',
                'sku' => 'RX-SALB-INH',
                'scientific_name' => 'Salbutamol Sulfate',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['beximco'],
                'unit_id' => $units['each'],
                'dosage_form' => 'Inhaler',
                'strength' => '100mcg/dose',
                'route_of_administration' => 'Inhalation',
                'purchase_with_tax' => 120.00,
                'sales_price' => 180.00,
                'wholesale_price' => 155.00,
                'alert_qty' => 8,
                'prescription_required' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Salbutamol',
                'stock_qty' => 0,
                'batch_no' => 'BATCH-2026-SB01',
                'expire_date' => '2027-07-01',
            ],

            // ── Controlled item ──
            [
                'productName' => 'Tramadol 50mg',
                'barcode' => '6001234567026',
                'sku' => 'RX-TRAM-050',
                'scientific_name' => 'Tramadol Hydrochloride',
                'category_id' => $categories['prescription'],
                'manufacturer_id' => $manufacturers['aci'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Capsule',
                'strength' => '50mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 60.00,
                'sales_price' => 88.00,
                'wholesale_price' => 75.00,
                'alert_qty' => 10,
                'prescription_required' => true,
                'controlled_item' => true,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Tramadol HCl',
                'stock_qty' => 25,
                'batch_no' => 'BATCH-2026-TR01',
                'expire_date' => '2027-10-20',
            ],

            // ── Vitamins & Supplements ──
            [
                'productName' => 'Vitamin C 1000mg',
                'barcode' => '6001234567027',
                'sku' => 'OTC-VITC-1G',
                'scientific_name' => 'Ascorbic Acid',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['acme'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '1000mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 25.00,
                'sales_price' => 42.00,
                'wholesale_price' => 35.00,
                'alert_qty' => 20,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Vitamin C',
                'stock_qty' => 180,
                'batch_no' => 'BATCH-2026-VC01',
                'expire_date' => '2028-05-15',
            ],
            [
                'productName' => 'Iron + Folic Acid',
                'barcode' => '6001234567028',
                'sku' => 'OTC-IRON-FOL',
                'scientific_name' => 'Ferrous Sulfate + Folic Acid',
                'category_id' => $categories['otc'],
                'manufacturer_id' => $manufacturers['square'],
                'unit_id' => $units['strip'],
                'dosage_form' => 'Tablet',
                'strength' => '150mg + 0.5mg',
                'route_of_administration' => 'Oral',
                'purchase_with_tax' => 10.00,
                'sales_price' => 18.00,
                'wholesale_price' => 14.00,
                'alert_qty' => 25,
                'prescription_required' => false,
                'track_inventory' => true,
                'track_expiration' => true,
                'active_ingredient' => 'Iron + Folic Acid',
                'stock_qty' => 250,
                'batch_no' => 'BATCH-2026-IF01',
                'expire_date' => '2028-02-20',
            ],
        ];

        foreach ($items as $item) {
            $stockQty = $item['stock_qty'];
            $batchNo = $item['batch_no'];
            $expireDate = $item['expire_date'];
            unset($item['stock_qty'], $item['batch_no'], $item['expire_date']);

            $item['business_id'] = $businessId;
            $item['active'] = true;
            $item['created_at'] = now();
            $item['updated_at'] = now();

            // Set stock_status
            $item['stock_status'] = match (true) {
                $stockQty <= 0 => 'out_of_stock',
                ($item['alert_qty'] ?? 0) > 0 && $stockQty <= ($item['alert_qty']) => 'low_stock',
                default => 'in_stock',
            };

            $product = Product::create($item);

            // Create stock batch
            Stock::create([
                'business_id' => $businessId,
                'product_id' => $product->id,
                'productStock' => $stockQty,
                'batch_no' => $batchNo,
                'expire_date' => $expireDate,
                'purchase_price' => $item['purchase_with_tax'],
                'barcode' => $item['barcode'] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function seedCategories(int $businessId): array
    {
        $map = [
            'prescription' => 'Prescription Medicine',
            'otc' => 'OTC Medicine',
            'baby' => 'Baby Care',
            'surgical' => 'Surgical Products',
        ];

        $ids = [];
        foreach ($map as $key => $name) {
            $cat = Category::firstOrCreate(
                ['categoryName' => $name, 'business_id' => $businessId],
                ['status' => 1, 'description' => $name, 'created_at' => now(), 'updated_at' => now()]
            );
            $ids[$key] = $cat->id;
        }

        return $ids;
    }

    private function seedManufacturers(int $businessId): array
    {
        $map = [
            'aci' => 'ACI Limited',
            'acme' => 'ACME Laboratories',
            'square' => 'Square Pharmaceuticals',
            'apc' => 'APC Pharma',
            'beximco' => 'Beximco Pharmaceuticals',
        ];

        $ids = [];
        foreach ($map as $key => $name) {
            $mfg = Manufacturer::firstOrCreate(
                ['name' => $name, 'business_id' => $businessId],
                ['status' => 1, 'created_at' => now(), 'updated_at' => now()]
            );
            $ids[$key] = $mfg->id;
        }

        return $ids;
    }

    private function seedUnits(int $businessId): array
    {
        $map = [
            'strip' => 'Strip',
            'box' => 'Box',
            'bottle' => 'Bottle',
            'each' => 'Each',
            'pack' => 'Pack',
        ];

        $ids = [];
        foreach ($map as $key => $name) {
            $unit = Unit::firstOrCreate(
                ['unitName' => $name, 'business_id' => $businessId],
                ['status' => 1, 'created_at' => now(), 'updated_at' => now()]
            );
            $ids[$key] = $unit->id;
        }

        return $ids;
    }
}
