-- =============================================================================
-- Z-Syst → Supabase sync script — 2026-10-01
-- =============================================================================
-- Applies the schema changes introduced on branch arena/01a0f4bb-z-syst to the
-- Supabase PostgreSQL database.
--
-- HOW TO RUN: Supabase Dashboard → SQL Editor → paste → Run
--             (or: psql "$SUPABASE_DB_URL" -f update_2026_10_01.sql)
--
-- The script is IDEMPOTENT and SELF-HEALING: every step checks that its
-- target table exists first, so a missing table cannot abort the other steps.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) businesses.status
--    Added to Laravel in database/migrations/2014_10_11_000001 (2026-10-01).
--    The admin panel toggles it via POST /admin/business/status/{id} and the
--    performance-index migration expects an index on this column.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF to_regclass('public.businesses') IS NOT NULL THEN
        ALTER TABLE public.businesses
            ADD COLUMN IF NOT EXISTS status boolean NOT NULL DEFAULT true;

        CREATE INDEX IF NOT EXISTS businesses_status_index
            ON public.businesses (status);

        RAISE NOTICE 'businesses.status applied';
    ELSE
        RAISE NOTICE 'SKIPPED: table public.businesses not found';
    END IF;
END
$$;

-- -----------------------------------------------------------------------------
-- 2) testimonials.status  (Landing module table)
--    Added by Modules/Landing/Database/migrations/2026_10_01_000001.
--    The landing API now returns only active testimonials.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF to_regclass('public.testimonials') IS NOT NULL THEN
        ALTER TABLE public.testimonials
            ADD COLUMN IF NOT EXISTS status boolean NOT NULL DEFAULT true;

        -- Keep every pre-existing testimonial visible.
        UPDATE public.testimonials SET status = true WHERE status IS NULL;

        RAISE NOTICE 'testimonials.status applied';
    ELSE
        RAISE NOTICE 'SKIPPED: table public.testimonials not found (see note below to create it)';
    END IF;
END
$$;

-- =============================================================================
-- 3) VERIFICATION QUERIES (read-only — inspect the results)
-- =============================================================================

-- 3.1 Both columns exist with the expected default:
SELECT table_name, column_name, data_type, column_default, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
  AND ((table_name = 'businesses'   AND column_name = 'status')
    OR (table_name = 'testimonials' AND column_name = 'status'))
ORDER BY table_name;

-- 3.2 RLS state for the touched tables (review against your policy set):
SELECT tablename, rowsecurity
FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN ('businesses', 'testimonials');

-- 3.3 Existing RLS policies on the touched tables (should remain in force):
SELECT tablename, policyname, permissive, cmd, qual, with_check
FROM pg_policies
WHERE schemaname = 'public'
  AND tablename IN ('businesses', 'testimonials');

-- =============================================================================
-- NOTES
-- =============================================================================
-- * No other schema change is required by the 2026-10-01 updates:
--     - the notification infrastructure reuses the existing `notifications`
--       table (database channel) — no DDL needed;
--     - mail/SMS delivery is application-side only;
--     - the ProductAnalyticsService fix is code-only.
-- * If `testimonials` does not exist in Supabase yet (Landing tables live in
--   module migrations), create it first with:
--
--     CREATE TABLE IF NOT EXISTS public.testimonials (
--         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--         text text,
--         star integer NOT NULL,
--         client_name text NOT NULL,
--         client_image text,
--         work_at text NOT NULL,
--         status boolean NOT NULL DEFAULT true,
--         created_at timestamptz DEFAULT now(),
--         updated_at timestamptz DEFAULT now()
--     );
--
--   then enable RLS and add policies consistent with your other public tables.
-- * If your Supabase schema stores these tables under different names
--   (camelCase vs snake_case reconciliation is an open task from the
--   2026-09-22 audit), adjust the table names above accordingly.
-- * Naming reconciliation (e.g. products."productName" vs
--   products.product_name) is NOT touched by this script.
