[program:horizon]
process_name=%(program_name)s
command=php /var/www/z-syst/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/z-syst/storage/logs/horizon.log
stopwaitsecs=3600
stopsignal=QUIT

[program:z-syst-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/z-syst/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/z-syst/storage/logs/worker.log
stopwaitsecs=3600

[program:z-syst-scheduler]
process_name=%(program_name)s
command=php /var/www/z-syst/artisan schedule:work
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/z-syst/storage/logs/scheduler.log

[group:z-syst]
programs=horizon,z-syst-worker,z-syst-scheduler
priority=999
