<?php

namespace Database\Factories;

use App\Models\Business;
use App\Models\Party;
use App\Models\PurchaseOrder;
use Illuminate\Database\Eloquent\Factories\Factory;

class PurchaseOrderFactory extends Factory
{
    protected $model = PurchaseOrder::class;

    public function definition(): array
    {
        return [
            // po_number is generated by the model's creating hook.
            'supplier_id' => Party::factory()->state(['type' => 'supplier']),
            'business_id' => Business::factory(),
            'status' => PurchaseOrder::STATUS_DRAFT,
            'priority' => PurchaseOrder::PRIORITY_NORMAL,
            'expected_delivery_date' => now()->addDays(7),
            'subtotal' => 0,
            'tax_amount' => 0,
            'discount_amount' => 0,
            'total_amount' => 0,
            'is_active' => true,
        ];
    }

    public function sent(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => PurchaseOrder::STATUS_SENT,
            'sent_at' => now(),
        ]);
    }
}
