<?php

namespace Database\Factories;

use App\Models\Business;
use App\Models\SupplierInvoice;
use App\Models\SupplierInvoicePayment;
use Illuminate\Database\Eloquent\Factories\Factory;

class SupplierInvoicePaymentFactory extends Factory
{
    protected $model = SupplierInvoicePayment::class;

    public function definition(): array
    {
        return [
            // payment_number is generated by the model's creating hook.
            'supplier_invoice_id' => SupplierInvoice::factory(),
            'business_id' => Business::factory(),
            'payment_date' => now(),
            'payment_method' => SupplierInvoicePayment::METHOD_CASH,
            'amount' => 100,
            'status' => SupplierInvoicePayment::STATUS_PENDING,
        ];
    }

    public function approved(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => SupplierInvoicePayment::STATUS_APPROVED,
            'approved_at' => now(),
        ]);
    }
}
