<?php

namespace App\Exceptions\Errors;

enum ErrorCode: string
{
    // Validation (VALIDATION_*)
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case VALIDATION_INVALID_INPUT = 'VALIDATION_INVALID_INPUT';
    case VALIDATION_MISSING_FIELD = 'VALIDATION_MISSING_FIELD';
    case VALIDATION_FILE_TOO_LARGE = 'VALIDATION_FILE_TOO_LARGE';
    case VALIDATION_INVALID_MIME = 'VALIDATION_INVALID_MIME';
    case VALIDATION_ROUTE_NOT_FOUND = 'VALIDATION_ROUTE_NOT_FOUND';
    case VALIDATION_METHOD_NOT_ALLOWED = 'VALIDATION_METHOD_NOT_ALLOWED';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';

    // Authentication (AUTH_*)
    case AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
    case AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED';
    case AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID';
    case AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED';
    case AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED';
    case AUTH_OTP_INVALID = 'AUTH_OTP_INVALID';
    case AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED';

    // Authorization (FORBIDDEN_*)
    case FORBIDDEN_ROLE = 'FORBIDDEN_ROLE';
    case FORBIDDEN_PERMISSION = 'FORBIDDEN_PERMISSION';

    // Business Rules (BUSINESS_*)
    case BUSINESS_INSUFFICIENT_STOCK = 'BUSINESS_INSUFFICIENT_STOCK';
    case BUSINESS_DUE_SALE_WALKING_CUSTOMER = 'BUSINESS_DUE_SALE_WALKING_CUSTOMER';
    case BUSINESS_PRESCRIPTION_ALREADY_USED = 'BUSINESS_PRESCRIPTION_ALREADY_USED';
    case BUSINESS_SALE_CANNOT_BE_DELETED = 'BUSINESS_SALE_CANNOT_BE_DELETED';
    case BUSINESS_DUPLICATE_ENTRY = 'BUSINESS_DUPLICATE_ENTRY';
    case BUSINESS_EMAIL_EXISTS = 'BUSINESS_EMAIL_EXISTS';
    case BUSINESS_LOGIN_ROLE_DENIED = 'BUSINESS_LOGIN_ROLE_DENIED';
    case BUSINESS_INVOICE_DUE_EXCEEDED = 'BUSINESS_INVOICE_DUE_EXCEEDED';
    case BUSINESS_OPENING_BALANCE_EXCEEDED = 'BUSINESS_OPENING_BALANCE_EXCEEDED';
    case BUSINESS_BATCH_QUANTITY_MISMATCH = 'BUSINESS_BATCH_QUANTITY_MISMATCH';
    case BUSINESS_INVOICE_NOT_FOUND = 'BUSINESS_INVOICE_NOT_FOUND';

    // Not Found (NOT_FOUND_*)
    case NOT_FOUND_RESOURCE = 'NOT_FOUND_RESOURCE';
    case NOT_FOUND_RELATION = 'NOT_FOUND_RELATION';
    case NOT_FOUND_BATCH = 'NOT_FOUND_BATCH';

    // External Services (EXTERNAL_*)
    case EXTERNAL_MAIL_UNCONFIGURED = 'EXTERNAL_MAIL_UNCONFIGURED';
    case EXTERNAL_MAIL_FAILED = 'EXTERNAL_MAIL_FAILED';
    case EXTERNAL_SMS_FAILED = 'EXTERNAL_SMS_FAILED';
    case EXTERNAL_PAYMENT_FAILED = 'EXTERNAL_PAYMENT_FAILED';

    // Upload (UPLOAD_*)
    case UPLOAD_STORAGE_FAILED = 'UPLOAD_STORAGE_FAILED';
    case UPLOAD_INVALID_FILE = 'UPLOAD_INVALID_FILE';
    case UPLOAD_NO_FILE = 'UPLOAD_NO_FILE';

    // System (SYSTEM_*)
    case SYSTEM_TRANSACTION_FAILED = 'SYSTEM_TRANSACTION_FAILED';
    case SYSTEM_INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR';
    case SYSTEM_MAINTENANCE_MODE = 'SYSTEM_MAINTENANCE_MODE';

    public function httpStatus(): int
    {
        return match ($this) {
            self::VALIDATION_FAILED,
            self::VALIDATION_INVALID_INPUT,
            self::VALIDATION_MISSING_FIELD,
            self::VALIDATION_FILE_TOO_LARGE,
            self::VALIDATION_INVALID_MIME,
            self::BUSINESS_INSUFFICIENT_STOCK,
            self::BUSINESS_DUE_SALE_WALKING_CUSTOMER,
            self::BUSINESS_PRESCRIPTION_ALREADY_USED,
            self::BUSINESS_BATCH_QUANTITY_MISMATCH,
            self::UPLOAD_INVALID_FILE,
            self::UPLOAD_STORAGE_FAILED,
            self::UPLOAD_NO_FILE => 422,

            self::AUTH_OTP_EXPIRED,
            self::AUTH_EMAIL_NOT_VERIFIED,
            self::BUSINESS_EMAIL_EXISTS,
            self::BUSINESS_DUPLICATE_ENTRY,
            self::BUSINESS_INVOICE_DUE_EXCEEDED,
            self::BUSINESS_OPENING_BALANCE_EXCEEDED => 409,

            self::AUTH_INVALID_CREDENTIALS,
            self::AUTH_TOKEN_EXPIRED,
            self::AUTH_TOKEN_INVALID,
            self::AUTH_OTP_INVALID => 401,

            self::FORBIDDEN_ROLE,
            self::FORBIDDEN_PERMISSION => 403,

            self::NOT_FOUND_RESOURCE,
            self::NOT_FOUND_RELATION,
            self::NOT_FOUND_BATCH,
            self::BUSINESS_INVOICE_NOT_FOUND => 404,

            self::VALIDATION_ROUTE_NOT_FOUND => 404,
            self::VALIDATION_METHOD_NOT_ALLOWED => 405,

            self::RATE_LIMIT_EXCEEDED => 429,

            self::EXTERNAL_MAIL_UNCONFIGURED,
            self::EXTERNAL_MAIL_FAILED,
            self::EXTERNAL_SMS_FAILED,
            self::EXTERNAL_PAYMENT_FAILED => 502,

            self::SYSTEM_TRANSACTION_FAILED,
            self::SYSTEM_INTERNAL_ERROR,
            self::SYSTEM_MAINTENANCE_MODE,
            self::BUSINESS_SALE_CANNOT_BE_DELETED,
            self::AUTH_UNAUTHORIZED => 500,
        };
    }

    public function logLevel(): string
    {
        return match ($this) {
            self::SYSTEM_TRANSACTION_FAILED,
            self::SYSTEM_INTERNAL_ERROR,
            self::SYSTEM_MAINTENANCE_MODE,
            self::EXTERNAL_MAIL_FAILED,
            self::EXTERNAL_SMS_FAILED,
            self::EXTERNAL_PAYMENT_FAILED => 'critical',

            self::FORBIDDEN_ROLE,
            self::FORBIDDEN_PERMISSION,
            self::AUTH_TOKEN_EXPIRED,
            self::AUTH_INVALID_CREDENTIALS,
            self::AUTH_TOKEN_INVALID,
            self::BUSINESS_INSUFFICIENT_STOCK,
            self::EXTERNAL_MAIL_UNCONFIGURED,
            self::BUSINESS_BATCH_QUANTITY_MISMATCH,
            self::BUSINESS_INVOICE_DUE_EXCEEDED,
            self::BUSINESS_OPENING_BALANCE_EXCEEDED => 'warning',

            default => 'info',
        };
    }

    public function shouldAlert(): bool
    {
        return in_array($this, [
            self::SYSTEM_TRANSACTION_FAILED,
            self::SYSTEM_INTERNAL_ERROR,
            self::EXTERNAL_MAIL_FAILED,
            self::EXTERNAL_SMS_FAILED,
            self::EXTERNAL_PAYMENT_FAILED,
            self::AUTH_TOKEN_EXPIRED,
        ]);
    }
}
