<?php

namespace App\Services\Settings;

/**
 * Central registry for all application setting definitions.
 *
 * Each entry defines: key, module, group, name, description, type,
 * default_value, validation_rules, scope permissions, and sort order.
 */
class SettingsRegistry
{
    /**
     * Get all setting definitions.
     *
     * @return array<string, array>
     */
    public static function all(): array
    {
        return array_merge(
            static::generalSettings(),
            static::salesSettings(),
            static::purchaseSettings(),
            static::inventorySettings(),
            static::productSettings(),
            static::invoiceSettings(),
            static::printingSettings(),
            static::barcodeSettings(),
            static::notificationSettings(),
            static::securitySettings(),
        );
    }

    /**
     * Group definitions by module.
     */
    public static function groupedByModule(): array
    {
        $all = static::all();
        $grouped = [];

        foreach ($all as $key => $definition) {
            $grouped[$definition['module']][$key] = $definition;
        }

        return $grouped;
    }

    /**
     * Get module metadata (label, icon, description).
     */
    public static function moduleMeta(): array
    {
        return [
            'general' => [
                'label' => 'General',
                'icon' => 'fas fa-cog',
                'description' => 'Organization name, currency, language, timezone, and other general preferences.',
            ],
            'sales' => [
                'label' => 'Sales',
                'icon' => 'fas fa-shopping-cart',
                'description' => 'Configure sales workflow, discounts, payments, and invoice behavior.',
            ],
            'purchases' => [
                'label' => 'Purchases',
                'icon' => 'fas fa-truck',
                'description' => 'Purchase workflow, cost calculation, supplier behavior, and approvals.',
            ],
            'inventory' => [
                'label' => 'Inventory',
                'icon' => 'fas fa-boxes',
                'description' => 'Stock management, negative stock, alerts, transfers, and adjustments.',
            ],
            'products' => [
                'label' => 'Products',
                'icon' => 'fas fa-cube',
                'description' => 'Product creation, SKU generation, barcodes, and pricing defaults.',
            ],
            'invoices' => [
                'label' => 'Invoices',
                'icon' => 'fas fa-file-invoice',
                'description' => 'Invoice numbering, templates, display options, and formatting.',
            ],
            'printing' => [
                'label' => 'Printing',
                'icon' => 'fas fa-print',
                'description' => 'Printer configuration, paper size, auto-print, and document printing.',
            ],
            'barcode' => [
                'label' => 'Barcode',
                'icon' => 'fas fa-barcode',
                'description' => 'Barcode scanner behavior, auto-focus, beep, and scan modes.',
            ],
            'notifications' => [
                'label' => 'Notifications',
                'icon' => 'fas fa-bell',
                'description' => 'Notification preferences for in-app, email, and sound alerts.',
            ],
            'security' => [
                'label' => 'Security',
                'icon' => 'fas fa-shield-alt',
                'description' => 'Security settings, session management, and access controls.',
            ],
        ];
    }

    protected static function generalSettings(): array
    {
        return [
            'general.currency' => [
                'key' => 'general.currency',
                'module' => 'general',
                'group' => 'localization',
                'name' => 'Default Currency',
                'description' => 'The default currency used throughout the application for displaying monetary values.',
                'type' => 'string',
                'default_value' => 'EGP',
                'validation_rules' => ['value' => 'required|string|max:10'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 10,
            ],
            'general.language' => [
                'key' => 'general.language',
                'module' => 'general',
                'group' => 'localization',
                'name' => 'Default Language',
                'description' => 'The default language for the application interface.',
                'type' => 'select',
                'type_options' => ['options' => [
                    ['value' => 'en', 'label' => 'English'],
                    ['value' => 'ar', 'label' => 'Arabic'],
                ]],
                'default_value' => 'en',
                'validation_rules' => ['value' => 'required|in:en,ar'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 20,
            ],
            'general.timezone' => [
                'key' => 'general.timezone',
                'module' => 'general',
                'group' => 'localization',
                'name' => 'Timezone',
                'description' => 'The default timezone used for dates and times throughout the application.',
                'type' => 'string',
                'default_value' => 'Africa/Cairo',
                'validation_rules' => ['value' => 'required|string'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 30,
            ],
            'general.date_format' => [
                'key' => 'general.date_format',
                'module' => 'general',
                'group' => 'localization',
                'name' => 'Date Format',
                'description' => 'The format used for displaying dates throughout the application.',
                'type' => 'select',
                'type_options' => ['options' => [
                    ['value' => 'd/m/Y', 'label' => 'DD/MM/YYYY'],
                    ['value' => 'm/d/Y', 'label' => 'MM/DD/YYYY'],
                    ['value' => 'Y-m-d', 'label' => 'YYYY-MM-DD'],
                    ['value' => 'd M, Y', 'label' => 'DD Mon, YYYY'],
                ]],
                'default_value' => 'd/m/Y',
                'validation_rules' => ['value' => 'required|string'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 40,
            ],
            'general.decimal_places' => [
                'key' => 'general.decimal_places',
                'module' => 'general',
                'group' => 'formatting',
                'name' => 'Decimal Places',
                'description' => 'Number of decimal places for monetary values.',
                'type' => 'integer',
                'default_value' => 2,
                'validation_rules' => ['value' => 'required|integer|between:0,6'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 50,
            ],
            'general.default_branch' => [
                'key' => 'general.default_branch',
                'module' => 'general',
                'group' => 'defaults',
                'name' => 'Default Branch',
                'description' => 'The default branch selected when creating new transactions.',
                'type' => 'integer',
                'default_value' => null,
                'validation_rules' => ['value' => 'nullable|integer'],
                'is_system_configurable' => false,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 60,
            ],
            'general.theme' => [
                'key' => 'general.theme',
                'module' => 'general',
                'group' => 'appearance',
                'name' => 'Theme',
                'description' => 'The visual theme for the application interface.',
                'type' => 'select',
                'type_options' => ['options' => [
                    ['value' => 'light', 'label' => 'Light'],
                    ['value' => 'dark', 'label' => 'Dark'],
                    ['value' => 'system', 'label' => 'System'],
                ]],
                'default_value' => 'light',
                'validation_rules' => ['value' => 'required|in:light,dark,system'],
                'is_system_configurable' => false,
                'is_organization_configurable' => false,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 70,
            ],
        ];
    }

    protected static function salesSettings(): array
    {
        return [
            'sales.allow_discount' => [
                'key' => 'sales.allow_discount',
                'module' => 'sales',
                'group' => 'discounts',
                'name' => 'Allow Discounts',
                'description' => 'Allow employees to apply discounts on sales invoices.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 10,
            ],
            'sales.max_discount_percent' => [
                'key' => 'sales.max_discount_percent',
                'module' => 'sales',
                'group' => 'discounts',
                'name' => 'Maximum Discount Percentage',
                'description' => 'The maximum discount percentage allowed on sales invoices.',
                'type' => 'decimal',
                'default_value' => 100,
                'validation_rules' => ['value' => 'required|numeric|between:0,100'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => false,
                'sort_order' => 20,
            ],
            'sales.allow_manual_price' => [
                'key' => 'sales.allow_manual_price',
                'module' => 'sales',
                'group' => 'pricing',
                'name' => 'Allow Manual Price Editing',
                'description' => 'Allow employees to manually change the selling price during a sale.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 30,
            ],
            'sales.auto_print' => [
                'key' => 'sales.auto_print',
                'module' => 'sales',
                'group' => 'printing',
                'name' => 'Auto Print Invoice',
                'description' => 'Automatically print the sales invoice after completion.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 40,
            ],
            'sales.auto_open_payment' => [
                'key' => 'sales.auto_open_payment',
                'module' => 'sales',
                'group' => 'workflow',
                'name' => 'Auto-Open Payment Dialog',
                'description' => 'Automatically open the payment dialog after adding items to the invoice.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 50,
            ],
            'sales.default_payment_method' => [
                'key' => 'sales.default_payment_method',
                'module' => 'sales',
                'group' => 'payments',
                'name' => 'Default Payment Method',
                'description' => 'The default payment method selected for new sales.',
                'type' => 'select',
                'type_options' => ['options' => [
                    ['value' => 'cash', 'label' => 'Cash'],
                    ['value' => 'card', 'label' => 'Card'],
                    ['value' => 'credit', 'label' => 'Credit'],
                    ['value' => 'bank_transfer', 'label' => 'Bank Transfer'],
                ]],
                'default_value' => 'cash',
                'validation_rules' => ['value' => 'required|string'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 60,
            ],
            'sales.allow_credit' => [
                'key' => 'sales.allow_credit',
                'module' => 'sales',
                'group' => 'payments',
                'name' => 'Allow Credit Sales',
                'description' => 'Allow selling on credit (due amount) to customers.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => false,
                'sort_order' => 70,
            ],
            'sales.allow_returns' => [
                'key' => 'sales.allow_returns',
                'module' => 'sales',
                'group' => 'returns',
                'name' => 'Allow Sales Returns',
                'description' => 'Allow employees to process sales returns.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => false,
                'sort_order' => 80,
            ],
            'sales.max_return_days' => [
                'key' => 'sales.max_return_days',
                'module' => 'sales',
                'group' => 'returns',
                'name' => 'Maximum Return Age (Days)',
                'description' => 'Maximum number of days after a sale when returns are allowed.',
                'type' => 'integer',
                'default_value' => 30,
                'validation_rules' => ['value' => 'required|integer|min:0'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 90,
            ],
            'sales.require_confirmation_delete' => [
                'key' => 'sales.require_confirmation_delete',
                'module' => 'sales',
                'group' => 'workflow',
                'name' => 'Require Confirmation Before Deleting',
                'description' => 'Require confirmation dialog before deleting a sales invoice.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 100,
            ],
            'sales.allow_selling_below_cost' => [
                'key' => 'sales.allow_selling_below_cost',
                'module' => 'sales',
                'group' => 'pricing',
                'name' => 'Allow Selling Below Purchase Cost',
                'description' => 'Allow employees to sell products at a price lower than the purchase cost.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => false,
                'sort_order' => 110,
            ],
            'sales.auto_new_invoice' => [
                'key' => 'sales.auto_new_invoice',
                'module' => 'sales',
                'group' => 'workflow',
                'name' => 'Auto Open New Invoice',
                'description' => 'Automatically open a new empty invoice after completing a sale.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 120,
            ],
            'sales.search_by_name' => [
                'key' => 'sales.search_by_name',
                'module' => 'sales',
                'group' => 'search',
                'name' => 'Product Search by Name',
                'description' => 'Allow searching for products by name in the sales screen.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 130,
            ],
            'sales.search_by_sku' => [
                'key' => 'sales.search_by_sku',
                'module' => 'sales',
                'group' => 'search',
                'name' => 'Product Search by SKU',
                'description' => 'Allow searching for products by SKU in the sales screen.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 140,
            ],
            'sales.search_by_barcode' => [
                'key' => 'sales.search_by_barcode',
                'module' => 'sales',
                'group' => 'search',
                'name' => 'Product Search by Barcode',
                'description' => 'Allow searching for products by barcode in the sales screen.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 150,
            ],
        ];
    }

    protected static function purchaseSettings(): array
    {
        return [
            'purchases.allow_edit_price' => [
                'key' => 'purchases.allow_edit_price',
                'module' => 'purchases',
                'group' => 'editing',
                'name' => 'Allow Editing Purchase Price',
                'description' => 'Allow employees to edit the purchase price when creating purchase invoices.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => false,
                'sort_order' => 10,
            ],
            'purchases.auto_print' => [
                'key' => 'purchases.auto_print',
                'module' => 'purchases',
                'group' => 'printing',
                'name' => 'Auto Print Purchase Invoice',
                'description' => 'Automatically print the purchase invoice after creation.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 20,
            ],
            'purchases.auto_update_cost' => [
                'key' => 'purchases.auto_update_cost',
                'module' => 'purchases',
                'group' => 'costing',
                'name' => 'Automatically Update Product Cost',
                'description' => 'Automatically update the product purchase cost when creating a purchase.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 30,
            ],
            'purchases.allow_returns' => [
                'key' => 'purchases.allow_returns',
                'module' => 'purchases',
                'group' => 'returns',
                'name' => 'Allow Purchase Returns',
                'description' => 'Allow employees to process purchase returns.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => false,
                'sort_order' => 40,
            ],
            'purchases.allow_create_product' => [
                'key' => 'purchases.allow_create_product',
                'module' => 'purchases',
                'group' => 'workflow',
                'name' => 'Allow Creating Products During Purchase',
                'description' => 'Allow employees to create new products directly from the purchase screen.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => false,
                'sort_order' => 50,
            ],
            'purchases.auto_numbering' => [
                'key' => 'purchases.auto_numbering',
                'module' => 'purchases',
                'group' => 'numbering',
                'name' => 'Automatic Purchase Numbering',
                'description' => 'Automatically generate sequential purchase invoice numbers.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 60,
            ],
        ];
    }

    protected static function inventorySettings(): array
    {
        return [
            'inventory.allow_negative_stock' => [
                'key' => 'inventory.allow_negative_stock',
                'module' => 'inventory',
                'group' => 'stock',
                'name' => 'Allow Negative Stock',
                'description' => 'Allow product stock to go below zero. When disabled, sales that would reduce stock below zero will be rejected.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 10,
            ],
            'inventory.low_stock_alert' => [
                'key' => 'inventory.low_stock_alert',
                'module' => 'inventory',
                'group' => 'alerts',
                'name' => 'Low Stock Alert',
                'description' => 'Enable low stock alerts for products.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 20,
            ],
            'inventory.low_stock_threshold' => [
                'key' => 'inventory.low_stock_threshold',
                'module' => 'inventory',
                'group' => 'alerts',
                'name' => 'Low Stock Threshold',
                'description' => 'The stock quantity below which a low stock alert is triggered.',
                'type' => 'integer',
                'default_value' => 10,
                'validation_rules' => ['value' => 'required|integer|min:0'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 30,
            ],
            'inventory.allow_manual_adjustments' => [
                'key' => 'inventory.allow_manual_adjustments',
                'module' => 'inventory',
                'group' => 'adjustments',
                'name' => 'Allow Manual Inventory Adjustments',
                'description' => 'Allow employees to manually adjust stock quantities.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => false,
                'sort_order' => 40,
            ],
            'inventory.allow_inter_branch_transfer' => [
                'key' => 'inventory.allow_inter_branch_transfer',
                'module' => 'inventory',
                'group' => 'transfers',
                'name' => 'Allow Inter-Branch Transfers',
                'description' => 'Allow stock transfers between branches.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => true,
                'is_user_configurable' => false,
                'sort_order' => 50,
            ],
            'inventory.require_transfer_approval' => [
                'key' => 'inventory.require_transfer_approval',
                'module' => 'inventory',
                'group' => 'transfers',
                'name' => 'Require Transfer Approval',
                'description' => 'Require manager approval before completing inter-branch stock transfers.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 60,
            ],
        ];
    }

    protected static function productSettings(): array
    {
        return [
            'products.auto_generate_sku' => [
                'key' => 'products.auto_generate_sku',
                'module' => 'products',
                'group' => 'creation',
                'name' => 'Auto-Generate SKU',
                'description' => 'Automatically generate SKU numbers for new products.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 10,
            ],
            'products.allow_duplicate_sku' => [
                'key' => 'products.allow_duplicate_sku',
                'module' => 'products',
                'group' => 'creation',
                'name' => 'Allow Duplicate SKU',
                'description' => 'Allow multiple products to share the same SKU.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 20,
            ],
            'products.default_tax' => [
                'key' => 'products.default_tax',
                'module' => 'products',
                'group' => 'defaults',
                'name' => 'Default Tax Rate',
                'description' => 'The default tax rate applied to new products.',
                'type' => 'decimal',
                'default_value' => 0,
                'validation_rules' => ['value' => 'required|numeric|between:0,100'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 30,
            ],
            'products.default_profit_margin' => [
                'key' => 'products.default_profit_margin',
                'module' => 'products',
                'group' => 'defaults',
                'name' => 'Default Profit Margin (%)',
                'description' => 'The default profit margin percentage used when calculating selling prices.',
                'type' => 'decimal',
                'default_value' => 25,
                'validation_rules' => ['value' => 'required|numeric|between:0,1000'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 40,
            ],
            'products.show_inactive' => [
                'key' => 'products.show_inactive',
                'module' => 'products',
                'group' => 'display',
                'name' => 'Show Inactive Products',
                'description' => 'Display inactive products in product lists and searches.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 50,
            ],
        ];
    }

    protected static function invoiceSettings(): array
    {
        return [
            'invoices.prefix' => [
                'key' => 'invoices.prefix',
                'module' => 'invoices',
                'group' => 'numbering',
                'name' => 'Invoice Prefix',
                'description' => 'A text prefix added before the invoice number (e.g., INV-, SALE-).',
                'type' => 'string',
                'default_value' => 'INV-',
                'validation_rules' => ['value' => 'nullable|string|max:20'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 10,
            ],
            'invoices.starting_number' => [
                'key' => 'invoices.starting_number',
                'module' => 'invoices',
                'group' => 'numbering',
                'name' => 'Starting Invoice Number',
                'description' => 'The next invoice number to use.',
                'type' => 'integer',
                'default_value' => 1,
                'validation_rules' => ['value' => 'required|integer|min:1'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 20,
            ],
            'invoices.reset_yearly' => [
                'key' => 'invoices.reset_yearly',
                'module' => 'invoices',
                'group' => 'numbering',
                'name' => 'Reset Numbering Per Year',
                'description' => 'Reset the invoice number sequence at the beginning of each year.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 30,
            ],
            'invoices.show_logo' => [
                'key' => 'invoices.show_logo',
                'module' => 'invoices',
                'group' => 'display',
                'name' => 'Show Organization Logo',
                'description' => 'Display the organization logo on printed invoices.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 40,
            ],
            'invoices.show_discount' => [
                'key' => 'invoices.show_discount',
                'module' => 'invoices',
                'group' => 'display',
                'name' => 'Show Discount on Invoice',
                'description' => 'Display discount amounts on printed invoices.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 50,
            ],
            'invoices.footer_text' => [
                'key' => 'invoices.footer_text',
                'module' => 'invoices',
                'group' => 'display',
                'name' => 'Invoice Footer Text',
                'description' => 'Custom text displayed at the bottom of invoices.',
                'type' => 'string',
                'default_value' => 'Thank you for your business!',
                'validation_rules' => ['value' => 'nullable|string|max:500'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 60,
            ],
        ];
    }

    protected static function printingSettings(): array
    {
        return [
            'printing.auto_print' => [
                'key' => 'printing.auto_print',
                'module' => 'printing',
                'group' => 'general',
                'name' => 'Enable Auto Print',
                'description' => 'Enable automatic printing for completed transactions.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 10,
            ],
            'printing.paper_size' => [
                'key' => 'printing.paper_size',
                'module' => 'printing',
                'group' => 'general',
                'name' => 'Default Paper Size',
                'description' => 'The default paper size used for printing documents.',
                'type' => 'select',
                'type_options' => ['options' => [
                    ['value' => 'thermal_80mm', 'label' => 'Thermal 80mm'],
                    ['value' => 'thermal_58mm', 'label' => 'Thermal 58mm'],
                    ['value' => 'a4', 'label' => 'A4'],
                    ['value' => 'letter', 'label' => 'Letter'],
                ]],
                'default_value' => 'a4',
                'validation_rules' => ['value' => 'required|string'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 20,
            ],
            'printing.copies' => [
                'key' => 'printing.copies',
                'module' => 'printing',
                'group' => 'general',
                'name' => 'Default Print Copies',
                'description' => 'The number of copies to print by default.',
                'type' => 'integer',
                'default_value' => 1,
                'validation_rules' => ['value' => 'required|integer|min:1|max:10'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 30,
            ],
            'printing.orientation' => [
                'key' => 'printing.orientation',
                'module' => 'printing',
                'group' => 'general',
                'name' => 'Print Orientation',
                'description' => 'The default page orientation for printed documents.',
                'type' => 'select',
                'type_options' => ['options' => [
                    ['value' => 'portrait', 'label' => 'Portrait'],
                    ['value' => 'landscape', 'label' => 'Landscape'],
                ]],
                'default_value' => 'portrait',
                'validation_rules' => ['value' => 'required|in:portrait,landscape'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 40,
            ],
            'printing.show_preview' => [
                'key' => 'printing.show_preview',
                'module' => 'printing',
                'group' => 'general',
                'name' => 'Show Print Preview',
                'description' => 'Show a print preview dialog before printing.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 50,
            ],
        ];
    }

    protected static function barcodeSettings(): array
    {
        return [
            'barcode.scanner_enabled' => [
                'key' => 'barcode.scanner_enabled',
                'module' => 'barcode',
                'group' => 'scanner',
                'name' => 'Scanner Enabled',
                'description' => 'Enable barcode scanner input mode.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 10,
            ],
            'barcode.auto_focus' => [
                'key' => 'barcode.auto_focus',
                'module' => 'barcode',
                'group' => 'scanner',
                'name' => 'Auto Focus',
                'description' => 'Automatically focus the barcode input field.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 20,
            ],
            'barcode.auto_submit' => [
                'key' => 'barcode.auto_submit',
                'module' => 'barcode',
                'group' => 'scanner',
                'name' => 'Auto Submit on Scan',
                'description' => 'Automatically submit the scanned barcode without requiring Enter.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 30,
            ],
            'barcode.beep' => [
                'key' => 'barcode.beep',
                'module' => 'barcode',
                'group' => 'scanner',
                'name' => 'Beep on Scan',
                'description' => 'Play a beep sound when a barcode is successfully scanned.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 40,
            ],
            'barcode.duplicate_prevention' => [
                'key' => 'barcode.duplicate_prevention',
                'module' => 'barcode',
                'group' => 'scanner',
                'name' => 'Duplicate Scan Prevention',
                'description' => 'Prevent scanning the same barcode twice in a row.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 50,
            ],
            'barcode.scan_timeout' => [
                'key' => 'barcode.scan_timeout',
                'module' => 'barcode',
                'group' => 'scanner',
                'name' => 'Scan Timeout (ms)',
                'description' => 'Maximum time in milliseconds to wait for a complete barcode scan.',
                'type' => 'integer',
                'default_value' => 100,
                'validation_rules' => ['value' => 'required|integer|min:50|max:5000'],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 60,
            ],
        ];
    }

    protected static function notificationSettings(): array
    {
        return [
            'notifications.in_app_enabled' => [
                'key' => 'notifications.in_app_enabled',
                'module' => 'notifications',
                'group' => 'channels',
                'name' => 'In-App Notifications',
                'description' => 'Enable in-app notification alerts.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 10,
            ],
            'notifications.sound_enabled' => [
                'key' => 'notifications.sound_enabled',
                'module' => 'notifications',
                'group' => 'channels',
                'name' => 'Sound Notifications',
                'description' => 'Play sound alerts for notifications.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 20,
            ],
            'notifications.low_stock_alert' => [
                'key' => 'notifications.low_stock_alert',
                'module' => 'notifications',
                'group' => 'categories',
                'name' => 'Low Stock Alerts',
                'description' => 'Receive notifications when product stock falls below the threshold.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 30,
            ],
            'notifications.sale_alert' => [
                'key' => 'notifications.sale_alert',
                'module' => 'notifications',
                'group' => 'categories',
                'name' => 'Sale Notifications',
                'description' => 'Receive notifications for new sales.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 40,
            ],
            'notifications.purchase_alert' => [
                'key' => 'notifications.purchase_alert',
                'module' => 'notifications',
                'group' => 'categories',
                'name' => 'Purchase Notifications',
                'description' => 'Receive notifications for new purchases.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => true,
                'is_role_configurable' => true,
                'is_user_configurable' => true,
                'sort_order' => 50,
            ],
            'notifications.security_alert' => [
                'key' => 'notifications.security_alert',
                'module' => 'notifications',
                'group' => 'categories',
                'name' => 'Security Alerts',
                'description' => 'Receive notifications for security events.',
                'type' => 'boolean',
                'default_value' => true,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => true,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 60,
            ],
        ];
    }

    protected static function securitySettings(): array
    {
        return [
            'security.session_lifetime' => [
                'key' => 'security.session_lifetime',
                'module' => 'security',
                'group' => 'session',
                'name' => 'Session Lifetime (minutes)',
                'description' => 'The number of minutes before an inactive session expires.',
                'type' => 'integer',
                'default_value' => 120,
                'validation_rules' => ['value' => 'required|integer|min:5|max:1440'],
                'is_system_configurable' => true,
                'is_organization_configurable' => false,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 10,
            ],
            'security.max_login_attempts' => [
                'key' => 'security.max_login_attempts',
                'module' => 'security',
                'group' => 'authentication',
                'name' => 'Max Login Attempts',
                'description' => 'Maximum number of failed login attempts before the account is locked.',
                'type' => 'integer',
                'default_value' => 5,
                'validation_rules' => ['value' => 'required|integer|min:1|max:20'],
                'is_system_configurable' => true,
                'is_organization_configurable' => false,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => false,
                'sort_order' => 20,
            ],
            'security.two_factor_enabled' => [
                'key' => 'security.two_factor_enabled',
                'module' => 'security',
                'group' => 'authentication',
                'name' => 'Enable Two-Factor Authentication',
                'description' => 'Require two-factor authentication for admin accounts.',
                'type' => 'boolean',
                'default_value' => false,
                'validation_rules' => [],
                'is_system_configurable' => true,
                'is_organization_configurable' => false,
                'is_branch_configurable' => false,
                'is_role_configurable' => false,
                'is_user_configurable' => true,
                'sort_order' => 30,
            ],
        ];
    }
}
