create table if not exists public.purchases (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.businesses(id) on delete cascade,
 party_id bigint references public.parties(id) on delete set null,
 user_id uuid references public.app_users(id) on delete set null,
 tax_id bigint references public.taxes(id) on delete set null,
 discount_amount numeric(14,2) not null default 0,
 tax_amount numeric(14,2) not null default 0,
 due_amount numeric(14,2) not null default 0,
 paid_amount numeric(14,2) not null default 0,
 total_amount numeric(14,2) not null default 0,
 invoice_number text,
 is_paid boolean not null default false,
 payment_type text not null default 'Cash',
 purchase_date timestamptz,
 purchase_data jsonb,
 note text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists purchases_business_date_idx on public.purchases(business_id,purchase_date);
create unique index if not exists purchases_business_invoice_uq on public.purchases(business_id,invoice_number) where invoice_number is not null;

create table if not exists public.purchase_items (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.businesses(id) on delete cascade,
 purchase_id bigint not null references public.purchases(id) on delete cascade,
 product_id bigint not null references public.products(id) on delete restrict,
 quantity integer not null default 0 check(quantity>=0),
 unit_price numeric(14,4) not null default 0,
 tax_amount numeric(14,2) not null default 0,
 discount_amount numeric(14,2) not null default 0,
 total_amount numeric(14,2) not null default 0,
 batch_no text,
 expire_date date,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists purchase_items_business_purchase_idx on public.purchase_items(business_id,purchase_id);

create table if not exists public.sales (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.businesses(id) on delete cascade,
 party_id bigint references public.parties(id) on delete set null,
 user_id uuid references public.app_users(id) on delete set null,
 tax_id bigint references public.taxes(id) on delete set null,
 discount_amount numeric(14,2) not null default 0,
 due_amount numeric(14,2) not null default 0,
 is_paid boolean not null default false,
 tax_amount numeric(14,2) not null default 0,
 paid_amount numeric(14,2) not null default 0,
 total_amount numeric(14,2) not null default 0,
 loss_profit numeric(14,2) not null default 0,
 payment_type text,
 invoice_number text,
 sale_date timestamptz,
 sale_data jsonb,
 meta jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists sales_business_date_idx on public.sales(business_id,sale_date);
create unique index if not exists sales_business_invoice_uq on public.sales(business_id,invoice_number) where invoice_number is not null;

create table if not exists public.sale_items (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.businesses(id) on delete cascade,
 sale_id bigint not null references public.sales(id) on delete cascade,
 product_id bigint not null references public.products(id) on delete restrict,
 quantity integer not null default 0 check(quantity>=0),
 unit_price numeric(14,4) not null default 0,
 tax_amount numeric(14,2) not null default 0,
 discount_amount numeric(14,2) not null default 0,
 total_amount numeric(14,2) not null default 0,
 batch_no text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists sale_items_business_sale_idx on public.sale_items(business_id,sale_id);

create table if not exists public.stock_movements (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.businesses(id) on delete cascade,
 product_id bigint not null references public.products(id) on delete restrict,
 warehouse_id bigint references public.warehouses(id) on delete set null,
 stock_id bigint references public.stocks(id) on delete set null,
 movement_type text not null,
 quantity integer not null,
 reference_type text,
 reference_id bigint,
 batch_no text,
 expire_date date,
 unit_cost numeric(14,4) not null default 0,
 notes text,
 created_by uuid references public.app_users(id) on delete set null,
 created_at timestamptz not null default now()
);
create index if not exists stock_movements_business_product_idx on public.stock_movements(business_id,product_id,created_at);
create index if not exists stock_movements_reference_idx on public.stock_movements(business_id,reference_type,reference_id);

do $$ declare t text; begin
 for t in select unnest(array['purchases','purchase_items','sales','sale_items','stock_movements'])
 loop
  execute format('alter table public.%I enable row level security',t);
  execute format('revoke all on table public.%I from anon, authenticated',t);
  execute format('grant select,insert,update,delete on table public.%I to authenticated',t);
  execute format('create policy %I_select on public.%I for select to authenticated using (business_id=(select public.current_business_id()))',t||'_tenant_select',t);
  execute format('create policy %I_insert on public.%I for insert to authenticated with check (business_id=(select public.current_business_id()))',t||'_tenant_insert',t);
  execute format('create policy %I_update on public.%I for update to authenticated using (business_id=(select public.current_business_id())) with check (business_id=(select public.current_business_id()))',t||'_tenant_update',t);
  execute format('create policy %I_delete on public.%I for delete to authenticated using (business_id=(select public.current_business_id()))',t||'_tenant_delete',t);
 end loop;
end $$;