alter table public.warehouses add constraint warehouses_business_id_uq unique(business_id,id);
alter table public.products add constraint products_business_id_uq unique(business_id,id);
create table public.stock_transfers (
 id bigint generated by default as identity primary key,business_id bigint not null references public.businesses(id) on delete cascade,
 from_warehouse_id bigint not null references public.warehouses(id) on delete cascade,to_warehouse_id bigint not null references public.warehouses(id) on delete cascade,
 product_id bigint not null references public.products(id) on delete restrict,quantity integer not null check(quantity>0),
 status text not null default 'pending',notes text,user_id uuid references public.app_users(id) on delete set null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(from_warehouse_id<>to_warehouse_id),
 foreign key(business_id,from_warehouse_id) references public.warehouses(business_id,id),
 foreign key(business_id,to_warehouse_id) references public.warehouses(business_id,id),
 foreign key(business_id,product_id) references public.products(business_id,id)
);
create index stock_transfers_business_status_idx on public.stock_transfers(business_id,status,created_at);
alter table public.stock_transfers enable row level security;
revoke all on table public.stock_transfers from anon,authenticated;
grant select,insert,update,delete on table public.stock_transfers to authenticated;
create policy stock_transfers_tenant_policy on public.stock_transfers for all to authenticated using (business_id=(select public.current_business_id())) with check (business_id=(select public.current_business_id()));