create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  company_name text not null,
  address text,
  phone_number text,
  picture_url text,
  will_expire date,
  subscription_date timestamptz,
  remaining_shop_balance numeric(12,2) not null default 0,
  shop_opening_balance numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_users (
  id uuid primary key references auth.users(id) on delete cascade,
  business_id bigint references public.businesses(id) on delete set null,
  name text,
  role text not null default 'staff',
  phone text,
  image text,
  lang text,
  status text not null default 'active',
  visibility jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_users_business_id_idx on public.app_users(business_id);

create or replace function public.current_business_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select business_id from public.app_users
  where id = (select auth.uid()) limit 1
$$;

revoke all on function public.current_business_id() from public;
grant execute on function public.current_business_id() to authenticated;

alter table public.businesses enable row level security;
alter table public.app_users enable row level security;

revoke all on table public.businesses from anon, authenticated;
revoke all on table public.app_users from anon, authenticated;

grant select, insert, update on table public.businesses to authenticated;
grant select, insert, update on table public.app_users to authenticated;

create policy businesses_select_own on public.businesses
for select to authenticated
using (id = (select public.current_business_id()));

create policy businesses_update_own on public.businesses
for update to authenticated
using (id = (select public.current_business_id()))
with check (id = (select public.current_business_id()));

create policy app_users_select_same_business on public.app_users
for select to authenticated
using (id = (select auth.uid()) or business_id = (select public.current_business_id()));

create policy app_users_update_self on public.app_users
for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy app_users_insert_self on public.app_users
for insert to authenticated
with check (id = (select auth.uid()));

comment on table public.businesses is 'Tenant/business root for Z-Syst.';
comment on table public.app_users is 'Supabase Auth user profile and Z-Syst tenant membership.';
