create table public.branches (id bigint generated by default as identity primary key,business_id bigint not null references public.businesses(id) on delete cascade,name text not null,code text not null,address text,phone text,manager_user_id uuid references public.app_users(id) on delete set null,is_default boolean not null default false,is_active boolean not null default true,metadata jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,code),unique(business_id,id));
alter table public.app_users add column if not exists branch_id bigint references public.branches(id) on delete set null;
alter table public.branches enable row level security;
alter table public.app_users enable row level security;
revoke all on table public.branches from anon,authenticated;
grant select,insert,update,delete on public.branches to authenticated;
create policy branches_tenant on public.branches for all to authenticated using (business_id=(select private.current_business_id())) with check (business_id=(select private.current_business_id()));
create index app_users_business_branch_idx on public.app_users(business_id,branch_id);
create index branches_business_active_idx on public.branches(business_id,is_active);