-- Z-Syst warehouse-aware batch traceability foundation
-- Adds warehouse-to-stock(batch) allocation while preserving legacy aggregate stock fallback.

create table if not exists public.warehouse_stock_batches (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  warehouse_id bigint not null references public.warehouses(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  stock_id bigint not null references public.stocks(id) on delete restrict,
  quantity integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint warehouse_stock_batches_quantity_nonnegative_chk check (quantity >= 0),
  constraint warehouse_stock_batches_unique unique (warehouse_id, product_id, stock_id)
);

create index if not exists warehouse_stock_batches_business_warehouse_product_idx
  on public.warehouse_stock_batches(business_id, warehouse_id, product_id);
create index if not exists warehouse_stock_batches_business_stock_idx
  on public.warehouse_stock_batches(business_id, stock_id);

alter table public.warehouse_stock_batches enable row level security;
drop policy if exists warehouse_stock_batches_tenant_policy on public.warehouse_stock_batches;
create policy warehouse_stock_batches_tenant_policy on public.warehouse_stock_batches
  using (business_id = private.current_business_id())
  with check (business_id = private.current_business_id());

create or replace function private.enforce_warehouse_stock_batch_business()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if not exists (select 1 from warehouses where id=new.warehouse_id and business_id=new.business_id) then
    raise exception 'Warehouse belongs to another business';
  end if;
  if not exists (select 1 from products where id=new.product_id and business_id=new.business_id) then
    raise exception 'Product belongs to another business';
  end if;
  if not exists (select 1 from stocks where id=new.stock_id and business_id=new.business_id and product_id=new.product_id) then
    raise exception 'Stock belongs to another business or product';
  end if;
  return new;
end$$;

drop trigger if exists warehouse_stock_batches_business_integrity on public.warehouse_stock_batches;
create trigger warehouse_stock_batches_business_integrity
before insert or update on public.warehouse_stock_batches
for each row execute function private.enforce_warehouse_stock_batch_business();

drop trigger if exists warehouse_stock_batches_updated_at on public.warehouse_stock_batches;
create trigger warehouse_stock_batches_updated_at
before update on public.warehouse_stock_batches
for each row execute function public.touch_updated_at();

-- The deployed receive_purchase, post_sale, post_purchase_return and
-- complete_stock_transfer functions were upgraded to populate/consume this
-- allocation table, apply tenant checks, preserve idempotency, block recalled
-- batches, and emit batch-aware stock/traceability movements.
