create extension if not exists pgtap with schema extensions;

create table if not exists public.financial_transactions (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.businesses(id) on delete cascade,
 transaction_type text not null,
 direction text not null check(direction in ('in','out')),
 payment_method text not null,
 amount numeric not null check(amount>0),
 reference_type text,
 reference_id bigint,
 register_id bigint references public.cash_registers(id) on delete set null,
 created_by uuid references public.app_users(id) on delete set null,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

alter table public.financial_transactions enable row level security;
drop policy if exists financial_transactions_tenant_select on public.financial_transactions;
create policy financial_transactions_tenant_select on public.financial_transactions
 for select to authenticated using(business_id=private.current_business_id());
drop policy if exists financial_transactions_tenant_insert on public.financial_transactions;
create policy financial_transactions_tenant_insert on public.financial_transactions
 for insert to authenticated with check(business_id=private.current_business_id());

create index if not exists financial_transactions_business_created_idx on public.financial_transactions(business_id,created_at desc);
create index if not exists financial_transactions_business_reference_idx on public.financial_transactions(business_id,reference_type,reference_id);
create unique index if not exists financial_transactions_source_unique_idx
 on public.financial_transactions(business_id,transaction_type,reference_type,reference_id,direction,payment_method)
 where reference_id is not null;

create or replace function public.enforce_child_same_business()
returns trigger language plpgsql set search_path=public,pg_temp as $$
declare v_parent_id bigint;
begin
 if tg_table_name='purchase_details' then v_parent_id:=(to_jsonb(new)->>'purchase_id')::bigint;
 elsif tg_table_name='sale_details' then v_parent_id:=(to_jsonb(new)->>'sale_id')::bigint;
 elsif tg_table_name='purchase_return_details' then v_parent_id:=(to_jsonb(new)->>'purchase_return_id')::bigint;
 elsif tg_table_name='sale_return_details' then v_parent_id:=(to_jsonb(new)->>'sale_return_id')::bigint;
 else return new;
 end if;
 if tg_table_name='purchase_details' and not exists(select 1 from purchases x where x.id=v_parent_id and x.business_id=new.business_id) then raise exception 'purchase belongs to another business'; end if;
 if tg_table_name='sale_details' and not exists(select 1 from sales x where x.id=v_parent_id and x.business_id=new.business_id) then raise exception 'sale belongs to another business'; end if;
 if tg_table_name='purchase_return_details' and not exists(select 1 from purchase_returns x where x.id=v_parent_id and x.business_id=new.business_id) then raise exception 'purchase return belongs to another business'; end if;
 if tg_table_name='sale_return_details' and not exists(select 1 from sale_returns x where x.id=v_parent_id and x.business_id=new.business_id) then raise exception 'sale return belongs to another business'; end if;
 return new;
end$$;

create or replace function private.record_financial_flow(
 p_business_id bigint,p_transaction_type text,p_direction text,p_payment_method text,p_amount numeric,
 p_reference_type text,p_reference_id bigint,p_register_id bigint default null,p_metadata jsonb default '{}'::jsonb
) returns bigint language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_id bigint;v_register bigint;v_user uuid:=auth.uid();
begin
 if p_business_id is distinct from private.current_business_id() then raise exception 'tenant mismatch'; end if;
 if p_amount<=0 then return null; end if;
 if p_direction not in('in','out') then raise exception 'invalid financial direction'; end if;
 if p_payment_method is null or btrim(p_payment_method)='' then raise exception 'payment method required'; end if;
 select id into v_id from financial_transactions
 where business_id=p_business_id and transaction_type=p_transaction_type and reference_type=p_reference_type
 and reference_id=p_reference_id and direction=p_direction and payment_method=lower(p_payment_method) limit 1;
 if v_id is not null then return v_id; end if;
 if lower(p_payment_method)='cash' then
   if p_register_id is not null then
     select id into v_register from cash_registers where id=p_register_id and business_id=p_business_id and status='open' for update;
   else
     select id into v_register from cash_registers where business_id=p_business_id and status='open' order by opened_at desc,id desc limit 1 for update;
   end if;
   if v_register is null then raise exception 'No open cash register for cash transaction'; end if;
 else
   v_register:=p_register_id;
   if v_register is not null and not exists(select 1 from cash_registers where id=v_register and business_id=p_business_id) then raise exception 'Invalid cash register'; end if;
 end if;
 insert into financial_transactions(business_id,transaction_type,direction,payment_method,amount,reference_type,reference_id,register_id,created_by,metadata)
 values(p_business_id,p_transaction_type,p_direction,lower(p_payment_method),p_amount,p_reference_type,p_reference_id,v_register,v_user,coalesce(p_metadata,'{}'::jsonb))
 on conflict (business_id,transaction_type,reference_type,reference_id,direction,payment_method)
 where reference_id is not null do nothing returning id into v_id;
 if v_id is null then
   select id into v_id from financial_transactions where business_id=p_business_id and transaction_type=p_transaction_type
   and reference_type=p_reference_type and reference_id=p_reference_id and direction=p_direction
   and payment_method=lower(p_payment_method) limit 1;
   return v_id;
 end if;
 if lower(p_payment_method)='cash' then
   insert into cash_register_transactions(business_id,register_id,type,amount,reference_type,reference_id,notes,created_by)
   values(p_business_id,v_register,case when p_direction='in' then 'cash_in' else 'cash_out' end,p_amount,p_reference_type,p_reference_id,p_transaction_type,v_user);
   update cash_registers set
    cash_sales=case when p_transaction_type='sale' and p_direction='in' then cash_sales+p_amount else cash_sales end,
    cash_refunds=case when p_transaction_type in('sale_return','purchase_return') and p_direction='out' then cash_refunds+p_amount else cash_refunds end,
    cash_in=case when p_direction='in' and p_transaction_type<>'sale' then cash_in+p_amount else cash_in end,
    cash_out=case when p_direction='out' and p_transaction_type not in('sale_return','purchase_return') then cash_out+p_amount else cash_out end,
    updated_at=now() where id=v_register;
 end if;
 return v_id;
end$$;

create or replace function public.api_post_sale_financial(
 p_business_id bigint,p_party_id bigint,p_warehouse_id bigint,p_invoice_number text,p_payment_type text,
 p_paid_amount numeric,p_discount_amount numeric,p_tax_amount numeric,p_items jsonb,
 p_idempotency_key text default null,p_register_id bigint default null
) returns bigint language plpgsql security invoker set search_path=public,private,pg_temp as $$
declare v_sale bigint;
begin
 v_sale:=private.post_sale($1,$2,$3,$4,$5,$6,$7,$8,$9,$10);
 if coalesce($6,0)>0 then
   perform private.record_financial_flow($1,'sale','in',$5,$6,'sale',v_sale,$11,jsonb_build_object('invoice_number',$4,'idempotency_key',$10));
 end if;
 return v_sale;
end$$;

create or replace function public.api_receive_purchase_financial(
 p_business_id bigint,p_party_id bigint,p_warehouse_id bigint,p_invoice_number text,p_payment_type text,
 p_paid_amount numeric,p_discount_amount numeric,p_tax_amount numeric,p_items jsonb,
 p_idempotency_key text default null,p_register_id bigint default null
) returns bigint language plpgsql security invoker set search_path=public,private,pg_temp as $$
declare v_purchase bigint;
begin
 v_purchase:=private.receive_purchase($1,$2,$3,$4,$5,$6,$7,$8,$9,$10);
 if coalesce($6,0)>0 then
   perform private.record_financial_flow($1,'purchase','out',$5,$6,'purchase',v_purchase,$11,jsonb_build_object('invoice_number',$4,'idempotency_key',$10));
 end if;
 return v_purchase;
end$$;

create or replace function public.api_post_sale_return_financial(
 p_business_id bigint,p_sale_id bigint,p_return_number text,p_items jsonb,p_reason text default null,p_register_id bigint default null
) returns bigint language plpgsql security invoker set search_path=public,private,pg_temp as $$
declare v_return bigint;v_refund numeric;
begin
 v_return:=private.post_sale_return($1,$2,$3,$4,$5);
 select refund_amount into v_refund from sale_returns where id=v_return and business_id=$1;
 if coalesce(v_refund,0)>0 then
   perform private.record_financial_flow($1,'sale_return','out',
    coalesce((select payment_type from sales where id=$2 and business_id=$1),'cash'),
    v_refund,'sale_return',v_return,$6,jsonb_build_object('sale_id',$2,'return_number',$3));
 end if;
 return v_return;
end$$;

create or replace function public.api_post_purchase_return_financial(
 p_purchase_id bigint,p_product_id bigint,p_quantity integer,p_stock_id bigint default null,
 p_refund_amount numeric default 0,p_notes text default null,p_register_id bigint default null
) returns bigint language plpgsql security invoker set search_path=public,private,pg_temp as $$
declare v_return bigint;v_payment text;v_business bigint:=private.current_business_id();
begin
 v_return:=(private.post_purchase_return($1,$2,$3,$4,$5,$6)).id;
 select payment_type into v_payment from purchases where id=$1 and business_id=v_business;
 if coalesce($5,0)>0 then
   perform private.record_financial_flow(v_business,'purchase_return','in',coalesce(v_payment,'cash'),$5,'purchase_return',v_return,$7,jsonb_build_object('purchase_id',$1,'product_id',$2,'quantity',$3));
 end if;
 return v_return;
end$$;

grant usage on schema private to authenticated;
grant execute on function private.post_sale(bigint,bigint,bigint,text,text,numeric,numeric,numeric,jsonb,text) to authenticated;
grant execute on function private.receive_purchase(bigint,bigint,bigint,text,text,numeric,numeric,numeric,jsonb,text) to authenticated;
grant execute on function private.post_sale_return(bigint,bigint,text,jsonb,text) to authenticated;
grant execute on function private.post_purchase_return(bigint,bigint,integer,bigint,numeric,text) to authenticated;
grant execute on function private.complete_stock_transfer(bigint) to authenticated;
grant execute on function private.record_financial_flow(bigint,text,text,text,numeric,text,bigint,bigint,jsonb) to authenticated;

revoke all on function public.api_post_sale_financial(bigint,bigint,bigint,text,text,numeric,numeric,numeric,jsonb,text,bigint) from public,anon;
revoke all on function public.api_receive_purchase_financial(bigint,bigint,bigint,text,text,numeric,numeric,numeric,jsonb,text,bigint) from public,anon;
revoke all on function public.api_post_sale_return_financial(bigint,bigint,text,jsonb,text,bigint) from public,anon;
revoke all on function public.api_post_purchase_return_financial(bigint,bigint,integer,bigint,numeric,text,bigint) from public,anon;
grant execute on function public.api_post_sale_financial(bigint,bigint,bigint,text,text,numeric,numeric,numeric,jsonb,text,bigint) to authenticated;
grant execute on function public.api_receive_purchase_financial(bigint,bigint,bigint,text,text,numeric,numeric,numeric,jsonb,text,bigint) to authenticated;
grant execute on function public.api_post_sale_return_financial(bigint,bigint,text,jsonb,text,bigint) to authenticated;
grant execute on function public.api_post_purchase_return_financial(bigint,bigint,integer,bigint,numeric,text,bigint) to authenticated;